name: ui_challenge
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_rating_bar: ^4.0.0
  flutter_search_bar: ^2.1.0
  font_awesome_flutter: ^9.2.0
  carousel_slider: ^4.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  fluttertoast: ^8.0.9 
  cupertino_icons: ^1.0.2 
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
  